// <auto-generated />
using System;
using ApiPontosTuristicos.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ApiPontosTuristicos.Migrations
{
    [DbContext(typeof(AppBdContext))]
    [Migration("20210702022109_cep2")]
    partial class cep2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.7");

            modelBuilder.Entity("ApiPontosTuristicos.Data.PontoTuristico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("CepPontoTuristico")
                        .HasColumnType("longtext");

                    b.Property<string>("CidadePontoTuristico")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("DataInclusaoPontoTuristico")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DescricaoPontoTuristico")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("EnderecoPontoTuristico")
                        .HasColumnType("longtext");

                    b.Property<string>("NomePontoTuristico")
                        .HasColumnType("longtext");

                    b.Property<string>("ReferenciaPontoTuristico")
                        .HasColumnType("longtext");

                    b.Property<string>("UfPontoTuristico")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("PontoTuristicos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CepPontoTuristico = "23575460",
                            CidadePontoTuristico = "Rio de Janeiro",
                            DataInclusaoPontoTuristico = new DateTime(2021, 6, 28, 17, 4, 32, 0, DateTimeKind.Unspecified),
                            DescricaoPontoTuristico = "Cristo Redentor é uma estátua art déco que retrata Jesus Cristo, localizada no topo do Corcovado.",
                            EnderecoPontoTuristico = "Parque Nacional da Tijuca",
                            NomePontoTuristico = "Cristo Redentor",
                            ReferenciaPontoTuristico = "",
                            UfPontoTuristico = "RJ"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
