// <auto-generated />
using ApiPontosTuristicos.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ApiPontosTuristicos.Migrations
{
    [DbContext(typeof(AppBdContext))]
    partial class AppBdContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.7");

            modelBuilder.Entity("ApiPontosTuristicos.Data.PontoTuristico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("CidadePontoTuristico")
                        .HasColumnType("longtext");

                    b.Property<string>("DescricaoPontoTuristico")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("EnderecoPontoTuristico")
                        .HasColumnType("longtext");

                    b.Property<string>("NomePontoTuristico")
                        .HasColumnType("longtext");

                    b.Property<string>("ReferenciaPontoTuristico")
                        .HasColumnType("longtext");

                    b.Property<string>("UfPontoTuristico")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("PontoTuristicos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CidadePontoTuristico = "Rio de Janeiro",
                            DescricaoPontoTuristico = "Grande",
                            EnderecoPontoTuristico = "Lapa",
                            NomePontoTuristico = "Cristo Reentor",
                            ReferenciaPontoTuristico = "",
                            UfPontoTuristico = "Rio de Janeiro"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
